# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "songyongkang"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "SLAM": 
        filters: ["SLAM", "Visual Odometry"]
    "Transformer": 
        filters: ["Transformer", "BEV"]
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Self Driving", "Self-Driving"]
    "LLM":
        filters: ["LLM", "Large Language Model", "Visual Language Model", "Multimodal Language Model"]
    "NeRF":
        filters: ["NeRF"]
